### ISSUE TITLE
StructurizrDslParserException when using a workspace with an inline Groovy script

### ISSUE THREAD

**Issue by dirkgroot** [avisi-cloud/structurizr-site-generatr#34]
When loading a workspace with an inline Groovy scripts, we get a stack trace. This can be fixed by packaging the `org.codehaus.groovy:groovy-jsr223` library with the app.

Stack trace:

```
java.lang.RuntimeException: Error running inline script, caused by java.lang.RuntimeException: Could not load a scripting engine for extension "groovy"
	at com.structurizr.dsl.InlineScriptDslContext.end(InlineScriptDslContext.java:43)
	at com.structurizr.dsl.StructurizrDslParser.endContext(StructurizrDslParser.java:841)
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:170)
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:125)
	at nl.avisi.structurizr.site.generatr.StructurizrUtilitiesKt.parseStructurizrDslWorkspace(StructurizrUtilities.kt:11)
	at nl.avisi.structurizr.site.generatr.ServeCommand.updateSite(ServeCommand.kt:50)
	at nl.avisi.structurizr.site.generatr.ServeCommand.execute(ServeCommand.kt:33)
	at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
	at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
	at nl.avisi.structurizr.site.generatr.AppKt.main(App.kt:13)
Caused by: java.lang.RuntimeException: Could not load a scripting engine for extension "groovy"
	at com.structurizr.dsl.ScriptDslContext.run(ScriptDslContext.java:26)
	at com.structurizr.dsl.InlineScriptDslContext.end(InlineScriptDslContext.java:41)
	... 9 more
Exception in thread "main" com.structurizr.dsl.StructurizrDslParserException: Error running inline script, caused by java.lang.RuntimeException: Could not load a scripting engine for extension "groovy" at line 19: }
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:778)
	at com.structurizr.dsl.StructurizrDslParser.parse(StructurizrDslParser.java:125)
	at nl.avisi.structurizr.site.generatr.StructurizrUtilitiesKt.parseStructurizrDslWorkspace(StructurizrUtilities.kt:11)
	at nl.avisi.structurizr.site.generatr.ServeCommand.updateSite(ServeCommand.kt:50)
	at nl.avisi.structurizr.site.generatr.ServeCommand.execute(ServeCommand.kt:33)
	at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
	at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
	at nl.avisi.structurizr.site.generatr.AppKt.main(App.kt:13)
```

**Comment by julrichkieffer** [comment]
[Structurizr supports several script engines](https://github.com/structurizr/dsl/tree/master/docs/cookbook/scripts), so take care to support all too.

> The !script keyword provides a way to run scripts written in Groovy, Kotlin, Ruby, and JavaScript.
