### ISSUE TITLE
Generating site on windows, exception - file referencing incorrect?

### ISSUE THREAD

**Issue by chipbite** [avisi-cloud/structurizr-site-generatr#463]
Hi! Very interesting tool.
I downloaded and ran this on windows. 

It started building the site tree and files, and got pretty far but after a while it throws the exception found here:

### java.nio.file.InvalidPathException: UNC path is missing sharename: /\index.html

```
C:\code\c4-demo-stuff\>"%JAVA_HOME%\bin\java.exe" -cp C:\temp\structurizr-site-generatr-1.1.7\lib\* nl.avisi.structurizr.site.generatr.AppKt generate-site -w space-c4.dsl
space_componentview...
corelib_componentview...
space_containerview...
space_Context...
Exception in thread "main" java.nio.file.InvalidPathException: UNC path is missing sharename: /\index.html
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:118)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
        at java.base/java.nio.file.Path.of(Path.java:148)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.writeHtmlFile(SiteGenerator.kt:206)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.access$writeHtmlFile(SiteGenerator.kt:1)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$1$1.invoke(SiteGenerator.kt:119)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$1$1.invoke(SiteGenerator.kt:119)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$2.invoke(SiteGenerator.kt:173)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$2.invoke(SiteGenerator.kt:173)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateHtmlFiles$lambda$20(SiteGenerator.kt:173)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

C:\code\c4-demo-stuff\>
```

_I looked briefly into it, but it was a while I coded java and have never coded kotlin, so I figured I'd let someone else with better familiarity look into it. Some file reference error it seems._

ℹ️ **Note:** The thing is, it has at this point succeeded in generating alot. (But links between the pages are not working at this point, at all.) So, it seems likely that there is a specific problem that is causing the file to not be referenced correctly.   It is not failing in general, much has been completed at this point.

BR! /marcus

------

PS
### Executing on windows, and in general 
1. The .bat script does **not** work (for me and I guess for anyone). The reason is that the classpath statement is too long and it yields and ["Input too long" error](https://stackoverflow.com/questions/1503708/problem-running-bat-file-on-windows-due-to-input-line-is-too-long), immediately.
So I ran it with a wildcard to lib folder instead, which works fine. The rest of the .bat file is just boilerplate/red tape and does not do anything. So this works, for example (I extracted to a folder in temp): 

```
java.exe" -cp C:\temp\structurizr-site-generatr-1.1.7\lib\* nl.avisi.structurizr.site.generatr.AppKt --help
```

Maybe the .bat script can be simplified. I could help and propose, if I get past the errors and get it to work... :-) 

2. I have several java versions, and I had to use version 20 for this too work. Version 17 did not work. So, therefore, I had to use %JAVA_HOME% to specify the version and I then __actually__ ran:
```
"%JAVA_HOME%\bin\java.exe" -cp C:\temp\structurizr-site-generatr-1.1.7\lib\* nl.avisi.structurizr.site.generatr.AppKt generate-site space-c4.dsl
```
Which was successful in starting execution and started to generate the site.

**Comment by dirkgroot** [comment]
Hi @chipbite,

Unfortunately I don't have easy access to a Windows machine. I have made a little change that might fix your issue. You can download the binaries containing this change using the following link: [potential fix](https://github.com/avisi-cloud/structurizr-site-generatr/actions/runs/8614889505/artifacts/1397500408).

Could you try if this fixes your issue? Thanks in advance!

**Comment by dirkgroot** [comment]
@chipbite I've updated the link in my previous comment to a build that includes the fix from #484.

**Comment by chipbite** [comment]
Hi @dirkgroot, great news - I will try this and get back to you!

**Comment by jp7677** [comment]
We don't use Java 21 specific features (yet), just changing https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/build.gradle.kts#L54 to e g. `17` locally should also work if installing JDK21 isn't that feasible.

**Comment by chipbite** [comment]
I have not built the source myself, but looking at the file you reference, @jp7677, it seems there are references to both v 21 and v 17:
https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/build.gradle.kts#L55-L64

https://github.com/avisi-cloud/structurizr-site-generatr/blob/5ed66707d3ac72a12dcbdf570acc80cd15f73027/build.gradle.kts#L55-L64

Theoretically, would it suffice to edit the jvmtoolchain value to 17 and run gradle?


(I will try adding java 21 to my system as well, I already have a few versions installed... )

**Comment by jp7677** [comment]
@chipbite You need to switch to the `fix-exception-on-windows` branch if you want to follow the work around I mentioned, `main` already contains https://github.com/avisi-cloud/structurizr-site-generatr/pull/486

**Comment by dirkgroot** [comment]
I've rebased the `fix-exception-on-windows` branch. [Here's a link]([binaries](https://github.com/avisi-cloud/structurizr-site-generatr/actions/runs/8634900545/artifacts/1402284949)) to the binaries that contain the potential fix and that are compabitle with Java 17.

**Comment by chipbite** [comment]
Tested. I installed java 21 and then it built the site without error ✔️  - with both the binaries you sent April 9th and now April 10th.

So, the error is gone, I run and it builds:

```
C:\code\c4-demo-stuff\ipex-architecture\c4-dsl\docs>"%JAVA_HOME%\bin\java.exe" -cp C:\temp\structurizr-site-generatr-1.1.7\lib\* nl.avisi.structurizr.site.generatr.AppKt generate-site -w c4-bank-demo-simplified.dsl
Components...

C:\code\c4-demo-stuff\ipex-architecture\c4-dsl\docs>"%JAVA_HOME%\bin\java.exe" --version
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Microsoft-8905927 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Microsoft-8905927 (build 21.0.2+13-LTS, mixed mode, sharing)
```

I also tried one of our own workspaces and the build process completes without error.

## Fix works.
The potential fix you have implemented solves this issue, and build runs without error on windows ([Version 10.0.19045.4170]).

### Java 17 using binaries from april 10th
I also tried running using `java 17` on windows using the rebased binaries and it also completes build without errors.

----

_So, thanks for this, now I got a locally built site... but I found a small link problem when browsing off of disk, #487._

**Comment by jp7677** [comment]
Could you please open a new issue, refer to this issue and also include details about what exactly goes wrong?

**Comment by chipbite** [comment]
Sure, will do. Its the same issue - same exception, like in the OP above.
```
Exception in thread "main" java.nio.file.InvalidPathException: UNC path is missing sharename: /\index.html
```
Created a new issue #499 for it.
