### ISSUE TITLE
1.0.14 NoSuchElementException: Collection contains no element matching the predicate

### ISSUE THREAD

**Issue by drazzib** [avisi-cloud/structurizr-site-generatr#93]
Using same DSL source file, static site generation works fine with **1.0.13** but fails since **1.0.14** (also tested with latest **1.0.16** which also fails)

`docker run -it --rm -v $HOME/xxxxx:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.13 generate-site --workspace-file dsl/main.dsl --default-branch master --version xyz9909` ➡️ 👍🏻

`docker run -it --rm -v $HOME/xxxx:/var/model ghcr.io/avisi-cloud/structurizr-site-generatr:1.0.14 generate-site --workspace-file dsl/main.dsl --default-branch master --version xyz9909` ➡️ 👎🏻 

**Exception** :
```
Exception in thread "main" java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateSite$generatorContext$1.invoke(SiteGenerator.kt:158)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateSite$generatorContext$1.invoke(SiteGenerator.kt:56)
        at nl.avisi.structurizr.site.generatr.site.views.MarkdownKt.transformEmbeddedDiagramElements(Markdown.kt:82)
        at nl.avisi.structurizr.site.generatr.site.views.MarkdownKt.markdownToHtml(Markdown.kt:43)
        at nl.avisi.structurizr.site.generatr.site.views.MarkdownKt.access$markdownToHtml(Markdown.kt:1)
        at nl.avisi.structurizr.site.generatr.site.views.MarkdownKt$markdown$1$1.invoke(Markdown.kt:25)
        at nl.avisi.structurizr.site.generatr.site.views.MarkdownKt$markdown$1$1.invoke(Markdown.kt:24)
        at kotlinx.html.stream.HTMLStreamBuilder.onTagContentUnsafe(stream.kt:87)
        at kotlinx.html.consumers.DelayedConsumer.onTagContentUnsafe(delayed-consumer.kt:58)
        at kotlinx.html.ApiKt.unsafe(api.kt:107)
        at nl.avisi.structurizr.site.generatr.site.views.MarkdownKt.markdown(Markdown.kt:24)
        at nl.avisi.structurizr.site.generatr.site.views.WorkspaceDecisionPageKt$workspaceDecisionPage$1$1.invoke(WorkspaceDecisionPage.kt:9)
        at nl.avisi.structurizr.site.generatr.site.views.WorkspaceDecisionPageKt$workspaceDecisionPage$1$1.invoke(WorkspaceDecisionPage.kt:8)
        at nl.avisi.structurizr.site.generatr.site.views.ContentDivKt.contentDiv(ContentDiv.kt:7)
        at nl.avisi.structurizr.site.generatr.site.views.WorkspaceDecisionPageKt$workspaceDecisionPage$1.invoke(WorkspaceDecisionPage.kt:8)
        at nl.avisi.structurizr.site.generatr.site.views.WorkspaceDecisionPageKt$workspaceDecisionPage$1.invoke(WorkspaceDecisionPage.kt:7)
        at nl.avisi.structurizr.site.generatr.site.views.PageKt.bodyFragment(Page.kt:42)
        at nl.avisi.structurizr.site.generatr.site.views.PageKt.page(Page.kt:12)
        at nl.avisi.structurizr.site.generatr.site.views.WorkspaceDecisionPageKt.workspaceDecisionPage(WorkspaceDecisionPage.kt:7)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.writeHtmlFile(SiteGenerator.kt:131)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.access$writeHtmlFile(SiteGenerator.kt:1)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$1$6$1.invoke(SiteGenerator.kt:88)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$1$6$1.invoke(SiteGenerator.kt:88)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$2.invoke(SiteGenerator.kt:111)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt$generateHtmlFiles$2.invoke(SiteGenerator.kt:111)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateHtmlFiles$lambda$14(SiteGenerator.kt:111)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
        at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
        at java.base/java.util.concurrent.CountedCompleter.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.invoke(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateHtmlFiles(SiteGenerator.kt:111)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateSite(SiteGenerator.kt:63)
        at nl.avisi.structurizr.site.generatr.site.SiteGeneratorKt.generateSite$default(SiteGenerator.kt:47)
        at nl.avisi.structurizr.site.generatr.GenerateSiteCommand.generateSiteForModel(GenerateSiteCommand.kt:99)
        at nl.avisi.structurizr.site.generatr.GenerateSiteCommand.execute(GenerateSiteCommand.kt:68)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:657)
        at kotlinx.cli.ArgParser.parse(ArgParser.kt:530)
        at nl.avisi.structurizr.site.generatr.AppKt.main(App.kt:13)
```

**Comment by dirkgroot** [comment]
Hi @drazzib, thanks for the report. Could you provide a Structurizr DSL workspace, that has this issue? A reproduction scenario would help a lot in fixing this.

**Comment by drazzib** [comment]
Hi @dirkgroot !

Finally, i've managed to found error in my DSL workspace 🔥 

One of my ADR Markdown content still reference **a view which don't existing anymore**
```
![](embed:notexistinganymore)
```

This error has been ignored by official structurizr cli and by previous version of structurizr-site-generatr (until 1.0.14)

@dirkgroot Do you think you can print missing element identifier in error message ? It would greatly help debug this kind of issue 💡

**Comment by dirkgroot** [comment]
@drazzib Ah, thanks for the clarification! It's certainly possible to show a useful error message in the generated website and in the  console output. We're already looking into that.
